-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
vim.keymap.del("n", "[b")
vim.keymap.del("n", "]b")
vim.keymap.del("n", "<leader>bb")
vim.keymap.del("n", "<leader>bD")
vim.keymap.del("n", "<leader>`")
vim.keymap.del("n", "<leader>|")
vim.keymap.del("n", "<leader>.")
vim.keymap.del("n", "<leader>S")
vim.keymap.del("n", "<leader>K")
vim.keymap.del("n", "<leader>L")
vim.keymap.del("n", "<leader>xq")
vim.keymap.del("n", "<leader>xl")
vim.keymap.del("n", "<leader><tab>l")
vim.keymap.del("n", "<leader><tab>o")
vim.keymap.del("n", "<leader><tab>f")
vim.keymap.del("n", "<leader><tab><tab>")
vim.keymap.del("n", "<leader><tab>]")
vim.keymap.del("n", "<leader><tab>d")
vim.keymap.del("n", "<leader><tab>[")
vim.keymap.del("n", "<leader>uz")
vim.keymap.del("n", "<leader>uZ")
vim.keymap.del("n", "<leader>wm")
vim.keymap.del("n", "<leader>wd")
vim.keymap.del("n", "<leader>ft")
vim.keymap.del("n", "<leader>fT")
vim.keymap.del("n", "<leader>ui")
vim.keymap.del("n", "<leader>uI")
vim.keymap.del({ "n", "x" }, "<leader>gB")
vim.keymap.del({ "n", "x" }, "<leader>gY")
vim.keymap.del("n", "<leader>gL")
vim.keymap.del("n", "<leader>gb")
vim.keymap.del("n", "<leader>uf")
vim.keymap.del("n", "<leader>uF")
vim.keymap.del("n", "<leader>ua")
vim.keymap.del("n", "<leader>uA")
vim.keymap.del("n", "<leader>ub")
vim.keymap.del("n", "<leader>uc")
vim.keymap.del("n", "<leader>uC")
vim.keymap.del("n", "<leader>ud")
vim.keymap.del("n", "<leader>uD")
vim.keymap.del("n", "<leader>ug")
vim.keymap.del("n", "<leader>ul")
vim.keymap.del("n", "<leader>uL")
vim.keymap.del("n", "<leader>un")
vim.keymap.del("n", "<leader>ur")
vim.keymap.del("n", "<leader>up")
vim.keymap.del("n", "<leader>us")
vim.keymap.del("n", "<leader>uS")
vim.keymap.del("n", "<leader>uT")
vim.keymap.del("n", "<leader>dpp")
vim.keymap.del("n", "<leader>dph")
vim.keymap.del("n", "<leader>dps")
vim.keymap.del("n", "<leader>uw")
vim.keymap.del("n", "<leader>cd")
vim.keymap.del("n", "<leader>qq")
vim.keymap.del("n", "<c-w><space>")
vim.keymap.del("n", "<c-w><c-d>")
vim.keymap.del("n", "<leader>sna")
vim.keymap.del("n", "<leader>snd")
vim.keymap.del("n", "<leader>snh")
vim.keymap.del("n", "<leader>snl")
vim.keymap.del("n", "<leader>snt")
vim.keymap.del("n", "<leader>?")

vim.keymap.set("i", "<A-Down>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move Down" })
vim.keymap.set("n", "<A-Up>", "<cmd>execute 'move .-' . (v:count1 + 1)<cr>==", { desc = "Move Up" })
vim.keymap.set("i", "<A-Up>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move Up" })
vim.keymap.set("v", "<A-Down>", ":<C-u>execute \"'<,'>move '>+\" . v:count1<cr>gv=gv", { desc = "Move Down" })
vim.keymap.set("n", "<A-Down>", "<cmd>execute 'move .+' . v:count1<cr>==", { desc = "Move Down" })
vim.keymap.set("v", "<A-Up>", ":<C-u>execute \"'<,'>move '<-\" . (v:count1 + 1)<cr>gv=gv", { desc = "Move Up" })

vim.keymap.set("n", "<leader>bd", function()
    Snacks.bufdelete()
end, { desc = "_b_uffer _d_elete" })
vim.keymap.set("n", "<leader>bo", function()
    Snacks.bufdelete.other()
end, { desc = "_b_uffer delete _o_thers" })

vim.keymap.set("n", "<leader>/", "<C-W>v", { desc = "split window horizontally" })
vim.keymap.set("n", "<leader>-", "<C-W>s", { desc = "split window vertically" })
vim.keymap.set("n", "<leader>l", "<cmd>Lazy<cr>", { desc = "_l_azy" })

vim.keymap.set("n", "<leader>wd", "<C-W>c", { desc = "Delete window", remap = true })

vim.keymap.set("n", "<leader>gl", function()
    Snacks.picker.git_log()
end, { desc = "_g_it _log_" })

vim.keymap.set("n", "<leader>gf", function()
    Snacks.picker.git_log_file()
end, { desc = "_g_it _f_ile history" })

if vim.fn.executable("lazygit") == 1 then
    vim.keymap.del("n", "<leader>gG")
    vim.keymap.set("n", "<leader>gg", function()
        Snacks.lazygit({ cwd = LazyVim.root.git() })
    end, { desc = "lazygit" })
end
if vim.lsp.inlay_hint then
    vim.keymap.del("n", "<leader>uh")
end

Snacks.toggle.option("wrap", { name = "_w_rap" }):map("<leader>ew")
