#!/bin/bash

# Function to convert a string to lowercase
lowercase() {
  echo "$1" | tr '[:upper:]' '[:lower:]'
}

# Check if a file is provided
if [ $# -eq 0 ]; then
  echo "Usage: scat <file|directory>"
  exit 1
fi

# Iterate over all files provided as arguments
for file in "$@"; do

  # Check if the file or directory exists
  if [ ! -e "$file" ]; then
    echo "File or directory not found: $file"
    continue
  fi

  # Handle directories
  if [ -d "$file" ]; then
    eza --tree --color=always "$file" | head -200 
    continue
  fi

  # Get the file extension and convert it to lowercase
  extension="${file##*.}"
  extension=$(lowercase "$extension")

  case "$extension" in
    # Markdown files
    md|markdown)
      mdcat "$file"
      ;;

    # PDF files 
    pdf)
      tdf "$file"
      ;;

    # Image files
    jpg|jpeg|png|gif|bmp|tiff)
      kitty +kitten icat "$file"
    ;;

    # Default to bat for other files
    *)
      bat "$file"
    ;;
  esac
done

